// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCt4bP7lcgiS64ug48PO3Q11YW4CeWWhoM',
    appId: '1:462620736112:web:ca0438d14c99dd715092b5',
    messagingSenderId: '462620736112',
    projectId: 'sk-robotics',
    authDomain: 'sk-robotics.firebaseapp.com',
    storageBucket: 'sk-robotics.firebasestorage.app',
    measurementId: 'G-RC3J43KLL4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC-P2P-vvt6nCPVuljY9Zz4BP14qUfV28U',
    appId: '1:462620736112:android:6225b20f80ea00065092b5',
    messagingSenderId: '462620736112',
    projectId: 'sk-robotics',
    storageBucket: 'sk-robotics.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD2_oFHJEwblcdP2cisbRN51TBlA6QMB0c',
    appId: '1:462620736112:ios:bd59de7c8e8861855092b5',
    messagingSenderId: '462620736112',
    projectId: 'sk-robotics',
    storageBucket: 'sk-robotics.firebasestorage.app',
    iosBundleId: 'com.example.skRobotics',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD2_oFHJEwblcdP2cisbRN51TBlA6QMB0c',
    appId: '1:462620736112:ios:bd59de7c8e8861855092b5',
    messagingSenderId: '462620736112',
    projectId: 'sk-robotics',
    storageBucket: 'sk-robotics.firebasestorage.app',
    iosBundleId: 'com.example.skRobotics',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCt4bP7lcgiS64ug48PO3Q11YW4CeWWhoM',
    appId: '1:462620736112:web:de8fdb4da18f498a5092b5',
    messagingSenderId: '462620736112',
    projectId: 'sk-robotics',
    authDomain: 'sk-robotics.firebaseapp.com',
    storageBucket: 'sk-robotics.firebasestorage.app',
    measurementId: 'G-DXTT3G6ENC',
  );
}
